ALTER TABLE entries ADD COLUMN last_changed TIMESTAMP NOT NULL DEFAULT 0;
ALTER TABLE entries ADD COLUMN last_author TEXT NOT NULL DEFAULT '';
ALTER TABLE entries ADD COLUMN size INTEGER NOT NULL DEFAULT 0;
