name: Publish
on:
  push:
    branches:
      - master
env:
  RUST_VERSION: nightly-2021-03-04
jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          override: true
          components: rustfmt, clippy
      - name: Restore Rust cache
        uses: Swatinem/rust-cache@v1
    
      - name: Run cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      
      - name: Tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.2
        with:
          custom_tag: ${{ github.sha }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: target/release/apertium-stats-service
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
